name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system

      - name: Set environment variable
        run: |
          echo "export DJANGO_SETTINGS_MODULE=api.coronavstech.coronavstech.settings" >> $GITHUB_ENV

      - name: Run manage.py shell
        run: |
          pipenv run python manage.py shell

      - name: Test with pytest
        run: |
          pipenv run pytest tests/ -s -v --durations=0 --cov=.
