name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --system

      - name: Set environment variable
        run: |
          export DJANGO_SETTINGS_MODULE=api.coronavstech.coronavstech.settings

      - name: Run pytest
        run: |
          pipenv run pytest tests/ -s -v --durations=0 --cov=.
