name: Python package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest allure-pytest pytest-django pipenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f Pipfile ]; then pipenv install; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Set environment variable
        run: |
          echo "DJANGO_SETTINGS_MODULE=api.coronavstech.coronavstech.settings" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/PycharmProjects/UDEMY-PythonTestAutomationWithPytest" >> $GITHUB_ENV

      - name: Run pytest on all files
        run: |
          pytest --alluredir=allure-results
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
          keep_reports: 20
          github_run_num: ${{ github.run_number }}
          github_run_id: ${{ github.run_id }}
          github_repo: ${{ github.repository }}
          github_repo_owner: ${{ github.repository_owner }}

      - name: Commit Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.MY_TOKEN_25 }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-report
